<Project Sdk="Microsoft.NET.Sdk">
	<Import Project="..\netfx.props"/>

	<PropertyGroup>
		<RootNamespace>Kaltura</RootNamespace>
		<AssemblyTitle>KalturaClient</AssemblyTitle>
		<Company>Kaltura</Company>
		<Product>KalturaClient</Product>
		<PackageId>Kaltura.Client</PackageId>
		<Description>Kaltura API Client Library</Description>
		<PackageTags>kaltura ott rest api client</PackageTags>
		<Copyright>Copyright (C) 2006-2019 Kaltura Inc.</Copyright>
		<Authors>Johnathan Amit-Kanarek, Arthur Vaverko, Jess Portnoy</Authors>
		<ProjectUrl>https://github.com/kaltura/KalturaOttGeneratedAPIClientsCsharp</ProjectUrl>
		<IconUrl>https://avatars2.githubusercontent.com/u/319096?s=200&amp;v=4</IconUrl>
		<Version>19.4.0</Version>
		<TargetFramework>net10.0</TargetFramework>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Newtonsoft.Json" Version="13.0.4"/>
	</ItemGroup>

</Project>